/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vezerlo;

import felulet.BalPanel;
import felulet.JobbPanel;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author Annamari
 */
public class MainFrame extends javax.swing.JFrame {

    private final int WIDTH = 1000;
    private final int HEIGHT = 700;
    
    private int xMouse;
    private int yMouse;
    
    
    public MainFrame() {
        setUndecorated(true);
        initComponents();
        beallitas();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        balPanel1 = new felulet.BalPanel();
        jobbPanel1 = new felulet.JobbPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().add(balPanel1, java.awt.BorderLayout.LINE_START);
        getContentPane().add(jobbPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       xMouse = evt.getX();
       yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().start();
                
            }
        });
    }

    private void beallitas() {
        this.setSize(WIDTH, HEIGHT);
        this.setLocationRelativeTo(null);
        UIManager.put("Button.disabledForeground", Color.RED);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private felulet.BalPanel balPanel1;
    private felulet.JobbPanel jobbPanel1;
    // End of variables declaration//GEN-END:variables

    private void start() {
        setVisible(true);
        Vezerlo vezerlo = new Vezerlo(jobbPanel1, balPanel1, this);
        balPanel1.setVezerlo(vezerlo);
        jobbPanel1.setVezerlo(vezerlo);
        vezerlo.beallitas();
    }

    public BalPanel getBalPanel1() {
        return balPanel1;
    }

    public JobbPanel getJobbPanel1() {
        return jobbPanel1;
    }
    
    
}
