/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felulet;

import java.awt.Graphics;
import vezerlo.Vezerlo;
import java.awt.Image;
import java.util.ResourceBundle;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Annamari
 */
public class BalPanel extends javax.swing.JPanel {

    private Vezerlo vezerlo;
    private Image hatter = new ImageIcon(this.getClass().getResource("/kepek/balhatter.png")).getImage(); 
    private int nyertjatekok;
    private int osszjatek;
    private ResourceBundle bundle;

    public void setBundle(ResourceBundle bundle) {
        this.bundle = bundle;
    }
    
    public void setNyertjatekok(int nyertjatekok) {
        this.nyertjatekok = nyertjatekok;
    }

    public void setOsszjatek(int osszjatek) {
        this.osszjatek = osszjatek;
    }
    public void setVezerlo(Vezerlo vezerlo) {
        this.vezerlo = vezerlo;
    }
    
    public BalPanel() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int kezdox, kezdoy, szelesseg, magassag;
	g.drawImage(hatter, 0, 0, this.getWidth(), this.getHeight(), this); 
        if(vezerlo!=null)
        {
            vezerlo.rajzol(g);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMasodik = new javax.swing.JLabel();
        lblElso = new javax.swing.JLabel();
        lblHarmadik = new javax.swing.JLabel();
        lblOtodik = new javax.swing.JLabel();
        lblNegyedik = new javax.swing.JLabel();
        lblHatodik = new javax.swing.JLabel();
        lblHetedik = new javax.swing.JLabel();
        lblNyolcadik = new javax.swing.JLabel();
        lblNyertJatekok = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(678, 700));
        setLayout(null);

        lblMasodik.setBackground(new java.awt.Color(153, 153, 153));
        lblMasodik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblMasodik.setForeground(new java.awt.Color(204, 204, 204));
        lblMasodik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMasodik.setText("2.");
        add(lblMasodik);
        lblMasodik.setBounds(199, 554, 51, 60);

        lblElso.setBackground(new java.awt.Color(153, 153, 153));
        lblElso.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblElso.setForeground(new java.awt.Color(204, 204, 204));
        lblElso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblElso.setText("1.");
        add(lblElso);
        lblElso.setBounds(199, 627, 51, 60);

        lblHarmadik.setBackground(new java.awt.Color(153, 153, 153));
        lblHarmadik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblHarmadik.setForeground(new java.awt.Color(204, 204, 204));
        lblHarmadik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarmadik.setText("3.");
        add(lblHarmadik);
        lblHarmadik.setBounds(199, 481, 51, 60);

        lblOtodik.setBackground(new java.awt.Color(153, 153, 153));
        lblOtodik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblOtodik.setForeground(new java.awt.Color(204, 204, 204));
        lblOtodik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOtodik.setText("5.");
        add(lblOtodik);
        lblOtodik.setBounds(199, 335, 51, 60);

        lblNegyedik.setBackground(new java.awt.Color(153, 153, 153));
        lblNegyedik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblNegyedik.setForeground(new java.awt.Color(204, 204, 204));
        lblNegyedik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNegyedik.setText("4.");
        add(lblNegyedik);
        lblNegyedik.setBounds(199, 408, 51, 60);

        lblHatodik.setBackground(new java.awt.Color(153, 153, 153));
        lblHatodik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblHatodik.setForeground(new java.awt.Color(204, 204, 204));
        lblHatodik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHatodik.setText("6.");
        add(lblHatodik);
        lblHatodik.setBounds(199, 262, 51, 60);

        lblHetedik.setBackground(new java.awt.Color(153, 153, 153));
        lblHetedik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblHetedik.setForeground(new java.awt.Color(204, 204, 204));
        lblHetedik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHetedik.setText("7.");
        add(lblHetedik);
        lblHetedik.setBounds(199, 189, 51, 60);

        lblNyolcadik.setBackground(new java.awt.Color(153, 153, 153));
        lblNyolcadik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblNyolcadik.setForeground(new java.awt.Color(204, 204, 204));
        lblNyolcadik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNyolcadik.setText("8.");
        add(lblNyolcadik);
        lblNyolcadik.setBounds(199, 116, 51, 60);

        lblNyertJatekok.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblNyertJatekok.setForeground(new java.awt.Color(0, 0, 0));
        lblNyertJatekok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNyertJatekok.setText("JatekNyeresekSzama");
        add(lblNyertJatekok);
        lblNyertJatekok.setBounds(266, 60, 200, 70);
        lblNyertJatekok.getAccessibleContext().setAccessibleName("lblNyertJatekok");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblElso;
    private javax.swing.JLabel lblHarmadik;
    private javax.swing.JLabel lblHatodik;
    private javax.swing.JLabel lblHetedik;
    private javax.swing.JLabel lblMasodik;
    private javax.swing.JLabel lblNegyedik;
    private javax.swing.JLabel lblNyertJatekok;
    private javax.swing.JLabel lblNyolcadik;
    private javax.swing.JLabel lblOtodik;
    // End of variables declaration//GEN-END:variables

    public void labeltAktival(int fuggolegesKor) {
        switch (fuggolegesKor) 
            {
                case 1: lblElso.setVisible(true); break;
                case 2: lblMasodik.setVisible(true); break;
                case 3: lblHarmadik.setVisible(true); break;
                case 4: lblNegyedik.setVisible(true); break;
                case 5: lblOtodik.setVisible(true); break;
                case 6: lblHatodik.setVisible(true); break;
                case 7: lblHetedik.setVisible(true); break;
                case 8: lblNyolcadik.setVisible(true); break;
            }
    }

    public void beallitas() {
        lblMasodik.setVisible(false);
        lblHarmadik.setVisible(false);
        lblNegyedik.setVisible(false);
        lblOtodik.setVisible(false);
        lblHatodik.setVisible(false);
        lblHetedik.setVisible(false);
        lblNyolcadik.setVisible(false);
    }

    public void lblFrissites() {
        lblNyertJatekok.setText(bundle.getString("nyertJatekok")+": \n" + nyertjatekok+"/"+osszjatek);
    }

    public JLabel getLblNyertJatekok() {
        return lblNyertJatekok;
    }
    
    


}
