/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felulet;

import java.awt.Graphics;
import vezerlo.Vezerlo;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Annamari
 */
public class BalPanel extends javax.swing.JPanel {

    private Vezerlo vezerlo;
    private Image hatter = new ImageIcon(this.getClass().getResource("/kepek/balhatter.png")).getImage(); 

    public void setVezerlo(Vezerlo vezerlo) {
        this.vezerlo = vezerlo;
    }
    
    public BalPanel() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int kezdox, kezdoy, szelesseg, magassag;
	g.drawImage(hatter, 0, 0, this.getWidth(), this.getHeight(), this); 
        if(vezerlo!=null)
        {
            vezerlo.rajzol(g);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMasodik = new javax.swing.JLabel();
        lblElso = new javax.swing.JLabel();
        lblHarmadik = new javax.swing.JLabel();
        lblOtodik = new javax.swing.JLabel();
        lblNegyedik = new javax.swing.JLabel();
        lblHatodik = new javax.swing.JLabel();
        lblHetedik = new javax.swing.JLabel();
        lblNyolcadik = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        lblMasodik.setBackground(new java.awt.Color(153, 153, 153));
        lblMasodik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblMasodik.setForeground(new java.awt.Color(204, 204, 204));
        lblMasodik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMasodik.setText("2.");

        lblElso.setBackground(new java.awt.Color(153, 153, 153));
        lblElso.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblElso.setForeground(new java.awt.Color(204, 204, 204));
        lblElso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblElso.setText("1.");

        lblHarmadik.setBackground(new java.awt.Color(153, 153, 153));
        lblHarmadik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblHarmadik.setForeground(new java.awt.Color(204, 204, 204));
        lblHarmadik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarmadik.setText("3.");

        lblOtodik.setBackground(new java.awt.Color(153, 153, 153));
        lblOtodik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblOtodik.setForeground(new java.awt.Color(204, 204, 204));
        lblOtodik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOtodik.setText("5.");

        lblNegyedik.setBackground(new java.awt.Color(153, 153, 153));
        lblNegyedik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblNegyedik.setForeground(new java.awt.Color(204, 204, 204));
        lblNegyedik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNegyedik.setText("4.");

        lblHatodik.setBackground(new java.awt.Color(153, 153, 153));
        lblHatodik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblHatodik.setForeground(new java.awt.Color(204, 204, 204));
        lblHatodik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHatodik.setText("6.");

        lblHetedik.setBackground(new java.awt.Color(153, 153, 153));
        lblHetedik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblHetedik.setForeground(new java.awt.Color(204, 204, 204));
        lblHetedik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHetedik.setText("7.");

        lblNyolcadik.setBackground(new java.awt.Color(153, 153, 153));
        lblNyolcadik.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblNyolcadik.setForeground(new java.awt.Color(204, 204, 204));
        lblNyolcadik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNyolcadik.setText("8.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNyolcadik, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHetedik, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHatodik, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOtodik, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHarmadik, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMasodik, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblElso, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNegyedik, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(428, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(lblNyolcadik, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblHetedik, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblHatodik, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblOtodik, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblNegyedik, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblHarmadik, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblMasodik, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblElso, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblElso;
    private javax.swing.JLabel lblHarmadik;
    private javax.swing.JLabel lblHatodik;
    private javax.swing.JLabel lblHetedik;
    private javax.swing.JLabel lblMasodik;
    private javax.swing.JLabel lblNegyedik;
    private javax.swing.JLabel lblNyolcadik;
    private javax.swing.JLabel lblOtodik;
    // End of variables declaration//GEN-END:variables

    public void labeltAktival(int fuggolegesKor) {
        switch (fuggolegesKor) 
            {
                case 1: lblElso.setVisible(true); break;
                case 2: lblMasodik.setVisible(true); break;
                case 3: lblHarmadik.setVisible(true); break;
                case 4: lblNegyedik.setVisible(true); break;
                case 5: lblOtodik.setVisible(true); break;
                case 6: lblHatodik.setVisible(true); break;
                case 7: lblHetedik.setVisible(true); break;
                case 8: lblNyolcadik.setVisible(true); break;
            }
    }

    public void beallitas() {
        lblMasodik.setVisible(false);
        lblHarmadik.setVisible(false);
        lblNegyedik.setVisible(false);
        lblOtodik.setVisible(false);
        lblHatodik.setVisible(false);
        lblHetedik.setVisible(false);
        lblNyolcadik.setVisible(false);
    }


}
