/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felulet;

import vezerlo.Vezerlo;

/**
 *
 * @author Annamari
 */
public class JatekVegeFrame extends javax.swing.JFrame {

    private final int SZELESSEG = 640;
    private final int MAGASSAG = 400;
    private int xMouse;
    private int yMouse;
    private Vezerlo vezerlo;
    
    public JatekVegeFrame() {
        setUndecorated(true);
        initComponents();
        beallitas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jatekVegePanel2 = new felulet.JatekVegePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().add(jatekVegePanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       xMouse = evt.getX();
       yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void beallitas() {
        this.setSize(SZELESSEG, MAGASSAG); 
        this.setLocationRelativeTo(this);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private felulet.JatekVegePanel jatekVegePanel2;
    // End of variables declaration//GEN-END:variables

    public JatekVegePanel getJatekVegePanel2() {
        return jatekVegePanel2;
    }
}
