/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felulet;

import java.awt.Color;
import vezerlo.Vezerlo;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ResourceBundle;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Annamari
 */
public class JobbPanel extends javax.swing.JPanel {

    private Image hatter = new ImageIcon(this.getClass().getResource("/kepek/hatter.jpg")).getImage(); 
    private ResourceBundle bundle;
    private Vezerlo vezerlo;
    private Icon hangbe = new ImageIcon(this.getClass().getResource("/kepek/hangbe.png")); 
    private Icon hangki = new ImageIcon(this.getClass().getResource("/kepek/hangki.png"));
    

    public void setVezerlo(Vezerlo vezerlo) {
        this.vezerlo = vezerlo;
    }
            
    public JobbPanel() {
        initComponents();
        btnHang.setIcon(hangki);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int kezdox, kezdoy, szelesseg, magassag;
	g.drawImage(hatter, 0, 0, this.getWidth(), this.getHeight(), null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIcon1 = new javax.swing.JButton();
        btnIcon2 = new javax.swing.JButton();
        btnIcon3 = new javax.swing.JButton();
        btnIcon4 = new javax.swing.JButton();
        btnIcon5 = new javax.swing.JButton();
        btnIcon6 = new javax.swing.JButton();
        btnIcon7 = new javax.swing.JButton();
        btnIcon8 = new javax.swing.JButton();
        btnIcon9 = new javax.swing.JButton();
        btnUjJatek = new javax.swing.JButton();
        btnKesz = new javax.swing.JButton();
        btnKilepes = new javax.swing.JButton();
        btnTalcara = new javax.swing.JButton();
        btnSugo = new javax.swing.JButton();
        btnVissza = new javax.swing.JButton();
        btnHun = new javax.swing.JButton();
        btnEng = new javax.swing.JButton();
        btnHang = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        btnIcon1.setBackground(new java.awt.Color(51, 51, 51));
        btnIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/01_ikon.png"))); // NOI18N
        btnIcon1.setMaximumSize(new java.awt.Dimension(424, 461));
        btnIcon1.setPreferredSize(new java.awt.Dimension(424, 461));
        btnIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcon1ActionPerformed(evt);
            }
        });

        btnIcon2.setBackground(new java.awt.Color(51, 51, 51));
        btnIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/02_ikon.png"))); // NOI18N
        btnIcon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcon2ActionPerformed(evt);
            }
        });

        btnIcon3.setBackground(new java.awt.Color(51, 51, 51));
        btnIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/03_ikon.png"))); // NOI18N
        btnIcon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcon3ActionPerformed(evt);
            }
        });

        btnIcon4.setBackground(new java.awt.Color(51, 51, 51));
        btnIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/04_ikon.png"))); // NOI18N
        btnIcon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcon4ActionPerformed(evt);
            }
        });

        btnIcon5.setBackground(new java.awt.Color(51, 51, 51));
        btnIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/05_ikon.png"))); // NOI18N
        btnIcon5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcon5ActionPerformed(evt);
            }
        });

        btnIcon6.setBackground(new java.awt.Color(51, 51, 51));
        btnIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/06_ikon.png"))); // NOI18N
        btnIcon6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcon6ActionPerformed(evt);
            }
        });

        btnIcon7.setBackground(new java.awt.Color(51, 51, 51));
        btnIcon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/07_ikon.png"))); // NOI18N
        btnIcon7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcon7ActionPerformed(evt);
            }
        });

        btnIcon8.setBackground(new java.awt.Color(51, 51, 51));
        btnIcon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/08_ikon.png"))); // NOI18N
        btnIcon8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcon8ActionPerformed(evt);
            }
        });

        btnIcon9.setBackground(new java.awt.Color(51, 51, 51));
        btnIcon9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/09_ikon.png"))); // NOI18N
        btnIcon9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcon9ActionPerformed(evt);
            }
        });

        btnUjJatek.setBackground(new java.awt.Color(51, 51, 51));
        btnUjJatek.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        btnUjJatek.setForeground(new java.awt.Color(0, 0, 0));
        btnUjJatek.setText("Új játék");
        btnUjJatek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjJatekActionPerformed(evt);
            }
        });

        btnKesz.setBackground(new java.awt.Color(51, 51, 51));
        btnKesz.setFont(new java.awt.Font("Vivaldi", 0, 70)); // NOI18N
        btnKesz.setText("Kész");
        btnKesz.setEnabled(false);
        btnKesz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeszActionPerformed(evt);
            }
        });

        btnKilepes.setBackground(new java.awt.Color(153, 0, 0));
        btnKilepes.setText("X");
        btnKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKilepesActionPerformed(evt);
            }
        });

        btnTalcara.setBackground(new java.awt.Color(51, 51, 51));
        btnTalcara.setText("_");
        btnTalcara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTalcaraActionPerformed(evt);
            }
        });

        btnSugo.setBackground(new java.awt.Color(0, 51, 102));
        btnSugo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSugo.setText("?");
        btnSugo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSugoActionPerformed(evt);
            }
        });

        btnVissza.setBackground(new java.awt.Color(51, 51, 51));
        btnVissza.setFont(new java.awt.Font("Vivaldi", 0, 48)); // NOI18N
        btnVissza.setText("Vissza");
        btnVissza.setEnabled(false);
        btnVissza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisszaActionPerformed(evt);
            }
        });

        btnHun.setBackground(new java.awt.Color(51, 51, 51));
        btnHun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/hun_flag.png"))); // NOI18N
        btnHun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHunActionPerformed(evt);
            }
        });

        btnEng.setBackground(new java.awt.Color(51, 51, 51));
        btnEng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/eng_flag.png"))); // NOI18N
        btnEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngActionPerformed(evt);
            }
        });

        btnHang.setBackground(new java.awt.Color(51, 51, 51));
        btnHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/hangki.png"))); // NOI18N
        btnHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnSugo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTalcara)
                        .addGap(1, 1, 1)
                        .addComponent(btnKilepes))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUjJatek, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnIcon7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnIcon8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnIcon9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btnKesz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnVissza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnHun, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnEng, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSugo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnKilepes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTalcara, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIcon8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIcon7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIcon9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKesz, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVissza, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEng, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHun, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUjJatek, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcon1ActionPerformed
        vezerlo.ikontBerak(1);
    }//GEN-LAST:event_btnIcon1ActionPerformed

    private void btnIcon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcon2ActionPerformed
        vezerlo.ikontBerak(2);
    }//GEN-LAST:event_btnIcon2ActionPerformed

    private void btnIcon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcon3ActionPerformed
        vezerlo.ikontBerak(3);
    }//GEN-LAST:event_btnIcon3ActionPerformed

    private void btnIcon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcon4ActionPerformed
        vezerlo.ikontBerak(4);
    }//GEN-LAST:event_btnIcon4ActionPerformed

    private void btnIcon5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcon5ActionPerformed
        vezerlo.ikontBerak(5);
    }//GEN-LAST:event_btnIcon5ActionPerformed

    private void btnIcon6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcon6ActionPerformed
        vezerlo.ikontBerak(6);
    }//GEN-LAST:event_btnIcon6ActionPerformed

    private void btnIcon7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcon7ActionPerformed
        vezerlo.ikontBerak(7);
    }//GEN-LAST:event_btnIcon7ActionPerformed

    private void btnIcon8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcon8ActionPerformed
        vezerlo.ikontBerak(8);
    }//GEN-LAST:event_btnIcon8ActionPerformed

    private void btnIcon9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcon9ActionPerformed
        vezerlo.ikontBerak(9);
    }//GEN-LAST:event_btnIcon9ActionPerformed

    private void btnVisszaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisszaActionPerformed
        vezerlo.visszaVon();
    }//GEN-LAST:event_btnVisszaActionPerformed

    private void btnKeszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeszActionPerformed
        vezerlo.keszenallas();
    }//GEN-LAST:event_btnKeszActionPerformed

    private void btnUjJatekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjJatekActionPerformed
        vezerlo.alaphelyzetbeallit();
        vezerlo.megoldastGyart();
        vezerlo.balpaneltBeallit();
    }//GEN-LAST:event_btnUjJatekActionPerformed

    private void btnTalcaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTalcaraActionPerformed
        vezerlo.talcaraRak();
    }//GEN-LAST:event_btnTalcaraActionPerformed

    private void btnKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKilepesActionPerformed
        vezerlo.dialogusAblak();
    }//GEN-LAST:event_btnKilepesActionPerformed

    private void btnSugoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSugoActionPerformed
        vezerlo.sugotMegnyit();
    }//GEN-LAST:event_btnSugoActionPerformed

    private void btnHunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHunActionPerformed
        vezerlo.bundleBeallitas("hu");
    }//GEN-LAST:event_btnHunActionPerformed

    private void btnEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngActionPerformed
        vezerlo.bundleBeallitas("en");
    }//GEN-LAST:event_btnEngActionPerformed

    private void btnHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangActionPerformed
        if(btnHang.getIcon().equals(hangki)){
            btnHang.setIcon(hangbe);
            vezerlo.zeneLeallitas();
            
        }
        else{
            vezerlo.zeneInditas();
            btnHang.setIcon(hangki);
        }
    }//GEN-LAST:event_btnHangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEng;
    private javax.swing.JButton btnHang;
    private javax.swing.JButton btnHun;
    private javax.swing.JButton btnIcon1;
    private javax.swing.JButton btnIcon2;
    private javax.swing.JButton btnIcon3;
    private javax.swing.JButton btnIcon4;
    private javax.swing.JButton btnIcon5;
    private javax.swing.JButton btnIcon6;
    private javax.swing.JButton btnIcon7;
    private javax.swing.JButton btnIcon8;
    private javax.swing.JButton btnIcon9;
    private javax.swing.JButton btnKesz;
    private javax.swing.JButton btnKilepes;
    private javax.swing.JButton btnSugo;
    private javax.swing.JButton btnTalcara;
    private javax.swing.JButton btnUjJatek;
    private javax.swing.JButton btnVissza;
    // End of variables declaration//GEN-END:variables

    public void keszenAlloGombBeallit(boolean aktivitas) {
        btnKesz.setEnabled(aktivitas);
        if(aktivitas)
        {
            btnKesz.requestFocus();
        }
    }

    public void visszaGombValtas(boolean aktivitas) {
        btnVissza.setEnabled(aktivitas);
    }

    public void osszesIkonGombotAktival(boolean aktivitas) {
        btnIcon1.setEnabled(aktivitas);
        btnIcon2.setEnabled(aktivitas);
        btnIcon3.setEnabled(aktivitas);
        btnIcon4.setEnabled(aktivitas);
        btnIcon5.setEnabled(aktivitas);
        btnIcon6.setEnabled(aktivitas);
        btnIcon7.setEnabled(aktivitas);
        btnIcon8.setEnabled(aktivitas);
        btnIcon9.setEnabled(aktivitas);
        
    }

    public void ikonGombAktivitastAllit(int iconIndex, boolean b) {
        switch(iconIndex)
        {
            case 1: btnIcon1.setEnabled(b); break;
            case 2: btnIcon2.setEnabled(b); break;
            case 3: btnIcon3.setEnabled(b); break;
            case 4: btnIcon4.setEnabled(b); break;
            case 5: btnIcon5.setEnabled(b); break;
            case 6: btnIcon6.setEnabled(b); break;
            case 7: btnIcon7.setEnabled(b); break;
            case 8: btnIcon8.setEnabled(b); break;
            case 9: btnIcon9.setEnabled(b); break;
        }
    }

    public void szovegBeallitas(ResourceBundle bundle) {
        btnKesz.setText(bundle.getString("btnKesz.text"));
        btnVissza.setText(bundle.getString("btnVissza.text"));
        btnUjJatek.setText(bundle.getString("btnUjJatek.text"));
    }
    
    public void ujJatekGombotBeallit(boolean b)
    {
        btnUjJatek.setEnabled(b);
    }
}
