/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felulet;

/**
 *
 * @author Annamari
 */
public class SugoFrame extends javax.swing.JFrame {

    private final int SZELESSEG = 350;
    private final int MAGASSAG = 280;
    
    public SugoFrame() {
        setUndecorated(true);
        initComponents();
        beallitas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sugoPanel2 = new felulet.SugoPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(sugoPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void beallitas() {
        this.setLocationRelativeTo(null);
        this.setSize(SZELESSEG, MAGASSAG);
    }

    public SugoPanel getSugoPanel2() {
        return sugoPanel2;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private felulet.SugoPanel sugoPanel2;
    // End of variables declaration//GEN-END:variables
}
